### ISSUE TITLE
Add configuration file

### ISSUE THREAD

**Issue by ziceptor** [codeHusky/Launchpads-Sponge#1]
1. In the config make option to disable throwing animals, mobs, etc.
2. Set the strength of the toss for the specified blocks.
3. Disable fall damage on the stove.
4. The possibility of using arbitrary blocks.
5. Economy. The price for the jump.
6. The number of positives (then remove)
7. Cooldown

**Comment by codeHusky** [comment]
Cool down kind of defeats the purpose of a pad.
I don't know what "number of positives is".
Price for a jump? Why.
I could implement arbitrary blocks easily in the config
I plan on disabling fall damage on the plates.
I can also do the disable animals thing.

**Comment by ziceptor** [comment]
> Cool down kind of defeats the purpose of a pad.

Rephrase, don't understand.
Recharge... customizable pause between jumps. Or the delay plate.

> Price for a jump? Why.

For quests, mini games... Many ways to use. Optional.

> The number of positives (then remove)
>  I don't know what "number of positives is".

The number of hops. For example, 3 jump... plate and the block is removed. For quests, mini games... Many ways to use.

How to use it will come up with every man for himself. For me it is useful.

Not necessary to have a framework for mini-games. Servers are not all production. Someone enough to have a few separate plugins.
